sudo: required
dist: trusty

#install google chrome, using addons
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sonarcloud:
    organization: "deepali-arvind-github" # the key of the org you chose at step #3
    token:
      secure: dc4853e8914c9517ec761b3bcea359289a8e85bf # encrypted value of your token   
 
language: node_js
node_js:
  - "8"

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
            
script: 
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner ; fi

cache:
  yarn: true
  
